# Задание

Используя материал занятия, документацию по библиотеке pandas и набор данных <a href='https://www.kaggle.com/gregorut/videogamesales'>Video Game Sales</a>:
1. Вывести все доступные платформы, на которых выпускалась хотя-бы одна игра;
2. Добавить к копии набора данных столбец metacritic_rating и заполнить его данными из набора данных <a href='https://www.kaggle.com/skateddu/metacritic-all-time-games-stats'>Metacritic all time games stats</a>;
3. Вывести список игр, рейтинг которых равен "M" и год издания не ранее 2012 года;
4. Рассчитать и вывести описательные статистики для списка, полученного в предыдущем пункте;
5. Вывести жанры игр с количеством игр, которые принадлежат соответствующему жанру в виде "<жанр> - <количество игр>" для всех жанров, которые содержат в своем названии не менее 3 различных гласных.

In [2]:
from pandas import Series, DataFrame
import pandas as pd

import numpy as np

In [3]:
df_vgs = pd.read_csv('vgsales.csv')
df_metacritic = pd.read_csv('metacritic_games.csv')

In [4]:
df_vgs.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

1. Вывести все доступные платформы, на которых выпускалась хотя-бы одна игра;

In [5]:
df_vgs["Platform"].unique()

array(['Wii', 'NES', 'GB', 'DS', 'X360', 'PS3', 'PS2', 'SNES', 'GBA',
       '3DS', 'PS4', 'N64', 'PS', 'XB', 'PC', '2600', 'PSP', 'XOne', 'GC',
       'WiiU', 'GEN', 'DC', 'PSV', 'SAT', 'SCD', 'WS', 'NG', 'TG16',
       '3DO', 'GG', 'PCFX'], dtype=object)

2. Добавить к копии набора данных столбец metacritic_rating и заполнить его данными из набора данных <a href='https://www.kaggle.com/skateddu/metacritic-all-time-games-stats'>Metacritic all time games stats;

In [6]:
df_metacritic.head()

,name,platform,developer,publisher,genre(s),players,rating,attribute,release_date,link,critic_positive,critic_neutral,critic_negative,metascore,user_positive,user_neutral,user_negative,user_score
0,Command & Conquer,PC,Westwood Studios,Virgin Interactive,Sci-Fi,1-4,T,NaN,"Aug 31, 1995",/game/pc/command-conquer,5,0,0,94,47,0,1,8.9
1,Full Throttle,PC,LucasArts,LucasArts,Adventure,NaN,NaN,NaN,"Apr 30, 1995",/game/pc/full-throttle,6,2,0,86,18,1,0,8.7
2,Battle Arena Toshinden,PS,Tamsoft,SCEA,Action,1-2,T,NaN,"Sep 9, 1995",/game/playstation/battle-arena-toshinden,1,3,0,69,1,0,1,5.8
3,Sid Meier's Civilization II,PC,MPS Labs,MicroProse,Strategy,1 Player,K-A,NaN,"Feb 29, 1996",/game/pc/sid-meiers-civilization-ii,7,0,0,94,46,0,1,8.9
4,Quake,PC,id Software,id Software,Action,1-16,M,NaN,"Jun 22, 1996",/game/pc/quake,9,0,0,94,84,4,1,8.8

In [7]:
merged_df = df_vgs.merge(df_metacritic[['name', 'rating']], how='left', left_on='Name', right_on='name')
merged_df.rename(columns={'rating': 'metacritic_rating'}, inplace=True)
merged_df.drop('name', axis=1, inplace=True)
merged_df.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,metacritic_rating
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,E
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,E
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,E
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN

3. Вывести список игр, рейтинг которых равен "M" и год издания не ранее 2012 года;

In [8]:
dop_df = merged_df[(merged_df['metacritic_rating']=='M') & (merged_df["Year"]>=2012)]
dop_df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,metacritic_rating
17,17,Grand Theft Auto V,PS3,2013.0,Action,Take-Two Interactive,7.01,9.27,0.97,4.14,21.40,M
18,17,Grand Theft Auto V,PS3,2013.0,Action,Take-Two Interactive,7.01,9.27,0.97,4.14,21.40,M
19,17,Grand Theft Auto V,PS3,2013.0,Action,Take-Two Interactive,7.01,9.27,0.97,4.14,21.40,M
20,17,Grand Theft Auto V,PS3,2013.0,Action,Take-Two Interactive,7.01,9.27,0.97,4.14,21.40,M
21,17,Grand Theft Auto V,PS3,2013.0,Action,Take-Two Interactive,7.01,9.27,0.97,4.14,21.40,M
...,...,...,...,...,...,...,...,...,...,...,...,...
28827,16402,The Technomancer,PC,2016.0,Role-Playing,Focus Home Interactive,0.00,0.01,0.00,0.00,0.01,M
28851,16419,Chaos;Child,PS3,2015.0,Adventure,5pb,0.00,0.00,0.01,0.00,0.01,M
28868,16432,Goat Simulator,XOne,2016.0,Simulation,Koch Media,0.00,0.01,0.00,0.00,0.01,M
29051,16572,Resident Evil 4 HD,XOne,2016.0,Shooter,Capcom,0.01,0.00,0.00,0.00,0.01,M
29052,16572,Resident Evil 4 HD,XOne,2016.0,Shooter,Capcom,0.01,0.00,0.00,0.00,0.01,M

4. Рассчитать и вывести описательные статистики для списка, полученного в предыдущем пункте;

In [9]:
dop_df.describe()

,Rank,Year,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
count,1336.000000,1336.000000,1336.00000,1336.000000,1336.000000,1336.000000,1336.000000
mean,5703.812874,2013.523204,0.54122,0.464880,0.047410,0.154192,1.207605
std,4487.946118,1.240177,1.15510,0.966549,0.116609,0.371218,2.454539
min,17.000000,2012.000000,0.00000,0.000000,0.000000,0.000000,0.010000
25%,1898.000000,2012.000000,0.05000,0.050000,0.000000,0.010000,0.140000
50%,4756.500000,2013.000000,0.15000,0.160000,0.000000,0.050000,0.410000
75%,9054.000000,2014.000000,0.47000,0.430000,0.040000,0.130000,1.080000
max,16572.000000,2016.000000,9.63000,9.270000,0.970000,4.140000,21.400000

5. Вывести жанры игр с количеством игр, которые принадлежат соответствующему жанру в виде "<жанр> - <количество игр>" для всех жанров, которые содержат в своем названии не менее 3 различных гласных.

In [10]:
def find_gener(word):
    vowels = set("aeiouAEIOU")
    count = 0
    for char in word:
        if char in vowels:
            count += 1
    return count

filtered_genres = df_vgs[df_vgs['Genre'].apply(lambda x: find_gener(x) >= 3)]#применяем функцию к каждому жанру
genre_counts_filtered = filtered_genres['Genre'].value_counts()

for genre, count in genre_counts_filtered.items():
    print(f"<{genre}> - <{count}>")

<Action> - <3316>
<Role-Playing> - <1488>
<Shooter> - <1310>
<Adventure> - <1286>
<Simulation> - <867>